### ISSUE TITLE
Serialization of DictField of ReferenceField

### ISSUE THREAD

**Issue by EloiZalczer** [hiroaki-yamamoto/mongoengine-goodjson#185] opened 2019-10-15 15:21 UTC
It appears that DictFields of ReferenceFields are not supported for serialization nor deserialization.

I have implemented the method for serialization and am currently working on the deserialization. I would be glad to propose a PR once I am done if you are interested ?

**Comment by hiroaki-yamamoto** [comment] 2019-10-16 01:38
Well, do you mind if I ask you more information (Doc Structure to reproduce bug / to improve the behavior)? e.g. I suppose that the document named `First` has a `DictField` named `emb` and the another document named `Second` references `First` then `to_json` doesn't serialize `emb`. i.e.

```
import mongoengine as db
import mongoengine_goodjson as gj

class First(gj.Document):
    emb = db.DictField() 

class Second(gj.Document):
    ref = db.ReferenceFIeld(First)
```

**Comment by EloiZalczer** [comment] 2019-10-16 08:00
Sure, sorry for the lack of precision. Here is a snippet:

```
class First(gj.Document):
    name = me.StringField()
    random= me.ReferenceField(SomeDocument, default=None)


class Second(gj.Document):
    name= me.StringField()
    firsts= me.DictField(me.ReferenceField(First))

    meta = {'allow_inheritance': True}
    meta = {'collection': 'second'}
```

The document._follow_reference method has a special case for db.ListField as the is_list variable, but does not seem to support db.DictField. I managed to make it work by adding a is_dict variable and implementing the following method, using the example of _follow_reference_list:

```
def __follow_reference_dict(self, fld, fldname, *args, **kwargs):
        """Follow reference with dict."""
        value = {}
        for (key, doc) in getattr(self, fldname).items():
            tdoc = fld.document_type.objects(
                id=doc.id
            ).get() if isinstance(doc, DBRef) else doc
            dct = self.__serialize_doc_to_dict(fld, tdoc, *args, **kwargs)
            value[key] = id_first(dct)
        return value
```

I hope it is clearer now :)

**Comment by hiroaki-yamamoto** [comment] 2019-10-16 10:13
Ok, this seems to be a bug.
I'll appreciate PR, but don't forget writing test 👍

**Comment by EloiZalczer** [comment] 2019-10-16 15:40
I created a PR for serialization, deserialization seems much harder to do and I'm not sure I will have time to do it so that's already something.

**Comment by hiroaki-yamamoto** [comment] 2019-10-17 00:42
Ok, thank you for the code. I'll merge it and push some fixes 👍

**Comment by EloiZalczer** [comment] 2019-11-28 12:47
Hello again !

Do you think you could merge this fix ? I am working with a team and I would love this improvement to be available in the pip release instead of having to use a local fix.

Thanks !

**Comment by hiroaki-yamamoto** [comment] 2019-11-29 09:34
Hi,

Yes, your commit is already merged on [fix/185-dictfield](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/commits/fix/185-dictfield) branch, but unfortunately I have no idea for de-serialization part....

I think you can pull https://github.com/hiroaki-yamamoto/mongoengine-goodjson/commit/57a056a78994b203f17a19006796a88ce96dd6a1 to use.

**Comment by EloiZalczer** [comment] 2019-11-29 15:00
I think I have managed to pull something off for the deserialization. However, the problem happens when saving the document. If the referenced documents are not saved, the DBRefs will just lead to an empty document. But we probably don't want to save the referenced documents on creation without asking the user.

The only solution that comes to my mind is to override the default _save_ method in the objects created by the deserialization, so that saving the top-level document recursively saves all referenced documents.

What do you think of this solution? If you are ok, I could try to implement it and propose a PR.

**Comment by hiroaki-yamamoto** [comment] 2019-12-07 00:42
Sorry for my response is delayed, because I move into Tokyo for my work.

As you can see [this](https://github.com/hiroaki-yamamoto/mongoengine-goodjson/blob/fix/185-dictfield/mongoengine_goodjson/document.py), you might know this package overrides `to_json` and `from_json`, and I don't mind overriding any default behavior. However, my stance is `use what is useful` that means you can leave the default behavior as-is, afap.

However, your (and any) PR will be appreciated though I don't accept it as you might know 😄

**Comment by EloiZalczer** [comment] 2019-12-13 12:49
Hello again,
I have opened a PR here: #207 
It is a work in progress but I would like you to review it and tell me what you think about it, and if it is worth continuing.
Thanks

**Comment by hiroaki-yamamoto** [comment] 2020-02-16 08:49
Merging & releasing done :+1:

**Closed by hiroaki-yamamoto** 2020-02-16 08:49 UTC
Labels: bug
